AWSTemplateFormatVersion: '2010-09-09'
Description: 'Simple backup infrastructure - S3 bucket with Glacier lifecycle and dedicated IAM user'

Parameters:
  BucketName:
    Type: String
    Description: 'Name for the backup bucket (must be globally unique)'
    Default: 'my-backup-bucket'

Resources:
  # S3 Bucket with Glacier Flexible lifecycle
  BackupBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${BucketName}-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: GlacierTransition
            Status: Enabled
            Transitions:
              - StorageClass: GLACIER
                TransitionInDays: 0  # Immediate transition to Glacier Flexible

  # Dedicated IAM user for backup operations only
  BackupUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub '${BucketName}-backup-user'
      Tags:
        - Key: Purpose
          Value: BackupOperations

  # Access key for backup user
  BackupUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref BackupUser

  # Minimal permissions policy - only this bucket
  BackupUserPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${BucketName}-backup-policy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # List bucket contents
          - Effect: Allow
            Action:
              - s3:ListBucket
              - s3:GetBucketLocation
            Resource: !GetAtt BackupBucket.Arn
          # Upload/download objects
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
            Resource: !Sub '${BackupBucket}/*'
          # Glacier restore operations
          - Effect: Allow
            Action:
              - s3:RestoreObject
            Resource: !Sub '${BackupBucket}/*'
      Users:
        - !Ref BackupUser

Outputs:
  BucketName:
    Description: 'S3 bucket name for backups'
    Value: !Ref BackupBucket
    Export:
      Name: !Sub '${BucketName}-bucket-name'

  AccessKeyId:
    Description: 'Access Key ID for backup user'
    Value: !Ref BackupUserAccessKey

  SecretAccessKey:
    Description: 'Secret Access Key for backup user (store securely)'
    Value: !GetAtt BackupUserAccessKey.SecretAccessKey

  Region:
    Description: 'AWS region for the bucket'
    Value: !Ref AWS::Region